SIM ?= icarus

VERILOG_SOURCES += $(PWD)/../src/alu_defs.sv
VERILOG_SOURCES += $(PWD)/../src/alu.sv
COCOTB_TOPLEVEL = alu
COCOTB_TEST_MODULES = test_alu

include $(shell cocotb-config --makefiles)/Makefile.sim