SIM ?= icarus

# VERILOG_SOURCES += $(PWD)/../src/*alu_defs.sv
VERILOG_SOURCES += $(PWD)/../src/extend.sv
COCOTB_TOPLEVEL = extend
COCOTB_TEST_MODULES = test_extend

include $(shell cocotb-config --makefiles)/Makefile.sim