SIM ?= icarus

# VERILOG_SOURCES += $(PWD)/../src/alu_defs.sv
VERILOG_SOURCES += $(PWD)/../src/register.sv
COCOTB_TOPLEVEL = register_file
COCOTB_TEST_MODULES = test_register

include $(shell cocotb-config --makefiles)/Makefile.sim